import type { Metadata } from 'next'

// These styles apply to every route in the application
import './globals.css'

// These ornaments apply to all page
import { OrnamentsContainer } from '@/containers/Ornaments/Ornaments.container'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <OrnamentsContainer />
        {children}
      </body>
    </html>
  )
}